on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 빌드
        run: ./gradlew build

      - name: JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar"
          target: "~/build/libs/"

      - name: 원격 서버에서 JAR 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
#            pkill -f 'java -jar.*week8-0.0.1-SNAPSHOT.jar' || true

            # JAR 파일 실행 (출력은 로그 파일로 리다이렉션)
            cd ~/build/libs/
            nohup java -jar week8-0.0.1-SNAPSHOT.jar &
            
            echo "애플리케이션이 시작되었습니다."
