on:
  push:
    branches:
      -main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 빌드
        run: ./gradlew build

      - name: 서버 배포
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p "$SERVER_PASSWORD" scp build/libs/*.jar $SERVER_USER@$SERVER_HOST:~/
          sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_HOST "pkill -f 'java -jar' || true; nohup java -jar *.jar &"
