on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v4

      - name: JDK 21 설정
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Gradle 빌드
        run: ./gradlew build

      - name: JAR 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "build/libs/*.jar"
          target: "~/build/libs/"

      - name: 원격 서버에서 JAR 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          sync: true
          script: |
            # JAR 파일 이름으로 프로세스 종료
            pkill -f 'java -jar.*week8-0.0.1-SNAPSHOT.jar' || true
            nohup java -jar ~/build/libs/week8-0.0.1-SNAPSHOT.jar &
            
            # 프로세스가 성공적으로 시작되었는지 확인
            sleep 5
            if pgrep -f 'java -jar.*week8-0.0.1-SNAPSHOT.jar' > /dev/null; then
            echo "애플리케이션이 성공적으로 시작되었습니다."
            else
            echo "애플리케이션 시작 실패!"
            exit 1
            fi
